### ISSUE TITLE
Make issue in `ariane-v0.7` branch

### ISSUE THREAD

**Issue by pcotret** [lowRISC/lowrisc-chip#203]
Followed instructions at: https://www.cl.cam.ac.uk/~jrrk2/docs/docs/
```bash
$ git clone -b ariane-v0.7 --recursive https://github.com/lowrisc/lowrisc-chip.git lowrisc-chip-ariane-v0.7
$ cd lowrisc-chip-ariane-v0.7
# Already installed Vivado, checked everything was fine
$ make nexys4_ddr_rocket
mkdir -p buildroot-2019.11.1-lowrisc/mainfs
cp buildroot-defconfig buildroot-2019.11.1-lowrisc/mainfs/.config
make -C buildroot-2019.11.1-lowrisc O=mainfs oldconfig
make[1]: Entering directory '/home/pascal/lowrisc-chip-ariane-v0.7/buildroot-2019.11.1-lowrisc'
make[2]: *** No rule to make target '/home/pascal/lowrisc-chip-ariane-v0.7/buildroot-2019.11.1-lowrisc/mainfs/.br2-external.mk'.  Stop.
make[1]: *** [Makefile:84: _all] Error 2
make[1]: Leaving directory '/home/pascal/lowrisc-chip-ariane-v0.7/buildroot-2019.11.1-lowrisc'
make: *** [Makefile:172: buildroot-2019.11.1-lowrisc/mainfs/.config] Error 2
```

**Comment by jrrk** [comment]
You did not capture the complete output, so I am guessing that one of your downloads did not complete, possibly due to the buildroot that was the latest thing at the time now being obsolete. I do not have access to a suitable Linux machine to reproduce the problem at the moment, and the project does not have a current maintainer. If you try 'git submodule update --init --recursive' this should show if any files are missing.

**Comment by pcotret** [comment]
No files are missing :(
I'll try something else later

**Comment by jrrk2** [comment]
I had the chance to try this again and I replicated your behaviour on a newer version of Ubuntu. Not sure what the fix is but you can try 'make buildroot -n -B|sh'. However this just moves the error on to a later stage where this version of build root is incompatible with the latest Ubuntu. The proper fix would be updating build root, but this is the last version that supports the old Berkley boot loader, for some reason Lowrisc does not support the newer boot loader architecture.
