### ISSUE TITLE
Failure during the toolchain build

### ISSUE THREAD

**Issue by noureddine-as** [lowRISC/lowrisc-chip#88]
Hi!
I would like to test the untethered version risc-v based SoC.

![image](https://user-images.githubusercontent.com/23646052/37661760-ccdc32ea-2c55-11e8-910d-fd6b8cacea03.png)
When i clone the repo and proceed to build the toolchain, i get this error, not sure if it's due to my network limitations or to something else?

I would like to understand please if the lowRISC SoC depends on a particular version of riscv-tools (gnu compilation toolchain / spike ...etc)? Or can I use a recent compilation toolchain with an old version of lowRISC? I mean by that if i change my hardware configuration (number of cores / accelerators / cache ...etc) do I need to rebuild the software toolchain/simulators? 

Thanks for taking time to respond my questions.
Best regards.

**Comment by jrrk** [comment]
That error could be caused by problems with nameservers or slow 
international links.

You cannot use the latest toolchain with lowrisc because it does not 
support compressed instructions and the ISA has changed (in particular 
control and status registers), and privilege instruction set.

However you do not need to recompile if you change the Knobs (number of 
cores etc.) as the ISA will be the same.

**Comment by noureddine-as** [comment]
It turned out that it's a network issue, i connected from another and that works.

Thanks for your answers @jrrk I'll dive deeper in the topic.
